version: "3.3"

volumes:
  data:

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306

  extension-app-dev:
    build:
      context: .
      dockerfile: ./.docker/extension-vite/Dockerfile
    volumes:
      - ./extension-vite:/app
      - /app/node_modules # create a volume, so no need to reinstall the node modules
    ports:
      - ${VITE_DEV_PORT}:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
