"""Initial migration

Revision ID: 0dc7367286cb
Revises: 
Create Date: 2023-06-13 01:30:30.465663

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0dc7367286cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('hashed_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_username'), 'user',
                    ['username'], unique=False)
    # ### end Alembic commands ###
    op.create_index(op.f("ix_user_id"), "user", [
                    "id"], unique=False)  # added index


def downgrade() -> None:
    op.drop_index(op.f("ix_user_id"), table_name="user")  # remove index
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
