"""remove payload from task

Revision ID: 2272f317cce3
Revises: bd7750d772d3
Create Date: 2023-07-05 19:58:02.026735

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2272f317cce3'
down_revision = 'bd7750d772d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_request', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_request', sa.Column('payload', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
