"""add timestamp to user table

Revision ID: 3953bcaa4500
Revises: 0dc7367286cb
Create Date: 2023-06-13 12:31:58.021838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3953bcaa4500'
down_revision = '0dc7367286cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_column('user', 'created_at')
    op.add_column('user', sa.Column('created_at', sa.DateTime(),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('user', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###
