"""add scan request table

Revision ID: 87b30cbe7d71
Revises: 2a12dcfad741
Create Date: 2023-06-19 17:02:05.014379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '87b30cbe7d71'
down_revision = '2a12dcfad741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_request',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_request_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_status_id', sa.Integer(), nullable=False),
    sa.Column('request_endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_information', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scan_status_id'], ['lookup.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_request')
    # ### end Alembic commands ###
