"""modify access key to nullable

Revision ID: 9634497e7435
Revises: 2a1548842ad0
Create Date: 2023-06-27 16:10:14.923701

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9634497e7435'
down_revision = '2a1548842ad0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'access_key',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'access_key',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
