"""add stopped_at to task table

Revision ID: 9e710473dd79
Revises: c12e299001c3
Create Date: 2023-06-27 19:01:53.455094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9e710473dd79'
down_revision = 'c12e299001c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('stopped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'stopped_at')
    # ### end Alembic commands ###
