"""move app_version to task

Revision ID: bd7750d772d3
Revises: ff8d49f35a59
Create Date: 2023-07-05 19:48:43.538722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd7750d772d3'
down_revision = 'ff8d49f35a59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_request', 'app_version')
    op.add_column('task', sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'app_version')
    op.add_column('scan_request', sa.Column('app_version', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
