"""add login trial and blocked_at to user table

Revision ID: ce1c889ad57d
Revises: c19bce2864ec
Create Date: 2023-07-20 19:23:28.760517

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce1c889ad57d'
down_revision = 'c19bce2864ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'login_trial', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column(
        'blocked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blocked_at')
    op.drop_column('user', 'login_trial')
    # ### end Alembic commands ###
