"""change to text instead of varchar for scan_request

Revision ID: dc93fb4a33e7
Revises: 2272f317cce3
Create Date: 2023-07-06 22:46:43.607844

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc93fb4a33e7'
down_revision = '2272f317cce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_request', 'original_request_data',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=mysql.TEXT(),
                    nullable=False)
    op.alter_column('scan_request', 'request_information',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=mysql.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_request', 'request_information',
                    existing_type=mysql.TEXT(),
                    type_=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('scan_request', 'original_request_data',
                    existing_type=mysql.TEXT(),
                    type_=mysql.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
