"""change start_at and end_at fields to nullable

Revision ID: ff8d49f35a59
Revises: 68836184b5a0
Create Date: 2023-07-05 18:57:15.137655

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff8d49f35a59'
down_revision = '68836184b5a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_request', 'start_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('scan_request', 'end_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_request', 'end_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('scan_request', 'start_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
